### PR TITLE
simplifyied cross project infrastructure

### PR DESCRIPTION
**Pull request by MasseGuillaume**
it's basically a copy paste of Scala.js crossProject adding .native* where needded

we need to address scala-native/58 (Make %%% work across different platforms)

### CODE REVIEW

**Comment by sjrd** [comment]
I have two concerns with this approach:

* It does not allow to create a cross-project that only has 2 targets (e.g., native and JVM, but not JS)
* sbt-cross-project now depends on Scala Native *and* on Scala.js. That means there is now way we can ever suggest this be made standard in sbt.

**Comment by MasseGuillaume** [comment]
> It does not allow to create a cross-project that only has 2 targets (e.g., native and JVM, but not JS)

If you don't define the concrete project it does not exists. For example:

```scala
lazy val foo = crossProject
lazy val fooJVM = foo.jvm
lazy val fooNative = foo.native
```

`fooJs` is not listed in the `projects` command

> sbt-cross-project now depends on Scala Native and on Scala.js. That means there is now way we can ever suggest this be made standard in sbt.

This is true. Do you have a use case of sbt-cross-project outside of native and js?

**Comment by densh** [comment]
I see the solution presented here as a simple, instantly useable, potentially imperfect step towards the final goal. A few things to love here:

- [x] Full source compatibility with existing Scala.js builds
- [x] Extremely simple and easy to understand codebase
- [x] No cryptic type errors

A few problems that @sjrd mentioned above seem to have simple work-arounds:

1. Cross-project against 2 out of three can be worked around as shown by @MasseGuillaume.
2. Dependency between sbt-cross-project and JS/Native can be made optional through some light use of reflection to check if those are currently available. 

IMO more generic all-encompasing solution can come later. If inclusion into mainline sbt is an ultimate goal, we should also discuss the design with sbt guys to see what they think about this.
Given that a working version of cross projects blocks our `0.1` release, I'd rather do it some time later in medium-term future and just settle on a simpler solution for now.

**Comment by sjrd** [comment]
OK if you are fine with those restrictions, well why not.

Regarding `%%%%`, IMO this is a bad idea. I suggest using `crossProject` and `%%%` anyway, and explain in the docs that people should use a specific import explicitly in their .sbt file. We can craft that import to shadow the auto-imported version from Scala.js (at least I hope so).

We should also investigate whether the new `derivedProjects`/`extraProjects` of sbt 0.13.13 could be leveraged to produce a better experience for sbt-cross-project. In particular I'm hoping we might be able to get rid of the extra `lazy val fooJS = foo.js` stuff. I'm bringing this up now because, if it can, it would invalidate the suggested workaround for 2/3 of the platforms.

**Comment by MasseGuillaume** [comment]
> Regarding `%%%%`, IMO this is a bad idea.
We are on the same page. I just wanted to experiment without modifying the scala-js-plugin. For the same reason, I renamed `crossProject` to `crossProject2`. When integrated `%%` and `crossProject` will be enough.

Regarding sbt import strategy the source is here: [EvaluateConfigurations.scala#L119](https://github.com/sbt/sbt/blob/57a655478f2fdf1de3e90acf2755b50c0459fd50/main/src/main/scala/sbt/internal/EvaluateConfigurations.scala#L119) and [Eval.scala#L81](https://github.com/sbt/sbt/blob/57a655478f2fdf1de3e90acf2755b50c0459fd50/main-actions/src/main/scala/sbt/compiler/Eval.scala#L81). I'm not a certified sbt developer but I think it translates to a sequence of imports and normal Scala import rules applies. The problem is then:

```scala
// plugin lang

object ScalaJsPlugin extends AutoPlugin {
  object autoImport {
    def crossProject = ???
  }
}

object ScalaNativePlugin extends AutoPlugin {
  object autoImport {
    // ...
  }
}

object SbtCrossPlugin extends AutoPlugin {
  object autoImport {
    def crossProject = ???
    // expr 1
  }
  override def requires = ScalaJsPlugin && ScalaNativePlugin
}
```

```scala
// user land
import ScalaJsPlugin.autoImport._
import ScalaNativePlugin.autoImport._ 
import SbtCrossPlugin.autoImport._
// expr 2
```

I suppose sbt has a partial ordering of the autoImports based on [auto plugins `requires`](http://www.scala-sbt.org/0.13/docs/Plugins.html#Implementing+plugin+dependencies)

can we find a `expr 1` (idealy) or a `expr 2`  such as `crossProject` resolved to `import SbtCrossPlugin.autoImport.crossProject`  (shadowing `import ScalaJsPlugin.autoImport.crossProject`) ?

**Comment by densh** [comment]
Me, @sjrd and @MasseGuillaume are going to discuss this ticket some time next week in person to finalise our discussion on shared cross projects between JS and Native.

**Comment by MasseGuillaume** [comment]
meeting minutes:

*  we solve the ambiguous import (`%%%` and `crossProject`) in userland by naming it. A named import has more precedence than a wildcard import.
* package name: `sbtcrossproject`
* `crossProject` enables platform via apply method, breaking source compatibility with current implementation `crossProject(JsPlatform, NativePlatform)`
* `xxxxxxSettings` are provided via implicit by platform's sbt plugin. `jvmSettings` is in the sbt-cross-project, `nativeSettings` is in sbt-native and `jsSettings` is in temporary `sbt-scalajs-cross-project`.
* we want to experiment with `extraproject` and `derivedproject`.
* native multi target (window vs linux, etc) is out of scope

**Comment by MasseGuillaume** [comment]
https://github.com/MasseGuillaume/sbt-cross-experiment

**Comment by MasseGuillaume** [comment]
@sjrd @densh this is what I have in terms of use case: https://github.com/MasseGuillaume/sbt-cross-experiment/blob/master/src/main/scala/userland/User.scala#L6

**Comment by MasseGuillaume** [comment]
https://github.com/scala-native/sbt-cross-project/pull/4

**Pull request closed without merging**
